"""New Migration

Revision ID: 0d146d55b6ce
Revises: ff01c6c12a69
Create Date: 2021-10-11 11:07:19.016152

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d146d55b6ce'
down_revision = 'ff01c6c12a69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
