"""New Migration

Revision ID: 5a225772f558
Revises: bfbec4133b5c
Create Date: 2021-09-26 11:00:43.231260

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a225772f558'
down_revision = 'bfbec4133b5c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
