"""New Migration

Revision ID: 67c73d146f9c
Revises: 235d81cf28a3
Create Date: 2021-10-18 07:08:22.470355

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67c73d146f9c'
down_revision = '235d81cf28a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
