"""New Migration

Revision ID: b8c37d349745
Revises: 209108a6fcdd
Create Date: 2021-09-26 10:02:08.720949

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8c37d349745'
down_revision = '209108a6fcdd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
