"""New Migration

Revision ID: bfbec4133b5c
Revises: b8c37d349745
Create Date: 2021-09-26 10:02:19.197221

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bfbec4133b5c'
down_revision = 'b8c37d349745'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
