"""New Migration

Revision ID: c4a23e84a7e4
Revises: 67c73d146f9c
Create Date: 2021-10-18 07:38:51.465608

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4a23e84a7e4'
down_revision = '67c73d146f9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
