"""New Migration

Revision ID: f3d747456c2f
Revises: 5a225772f558
Create Date: 2021-10-07 05:06:58.958967

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3d747456c2f'
down_revision = '5a225772f558'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
